# tox.ini
[tox]
minversion = 3.25.0
envlist = py39-molecule-podman
skipsdist = true

[testenv:py39-molecule-podman]
description = Run lightweight Molecule scenario with Podman driver
basepython = python3.9  # 👈 Явно указываем Python 3.9
passenv =
    HOME
    SSH_AUTH_SOCK
    XDG_RUNTIME_DIR
    PATH
deps =
    ansible-core>=2.12
    molecule>=6.0
    molecule-plugins  # 👈 Без [podman], драйвер подхватится автоматически
    ansible-lint>=6.0
    yamllint>=1.28
commands =
    molecule test -s podman-light --driver-name podman